<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario puntos',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada de reCAPTCHA 2.0 no válida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta de servidor de reCAPTCHA 2.0 no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => 'rfuentesp@sadasi.com',
		'to' => 'rfuentesp@sadasi.com,cbgarciaa@sadasi.com'
	),
	'fields' => array(
		'custom_U6277' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nombre',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombre\' es obligatorio.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Fecha de nacimiento',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Fecha de nacimiento\' es obligatorio.',
				'format' => 'El campo \'Fecha de nacimiento\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U6321' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Numero de teléfono',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Numero de teléfono\' es obligatorio.'
			)
		),
		'custom_U6338' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Numero de seguro social',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Numero de seguro social\' es obligatorio.'
			)
		)
	)
);

process_form($form);
?>
